spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:sqlite:simplelauncher.db?date_string_format=yyyy-MM-dd HH:mm:ss
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 3
      connection-timeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        show_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: error
        type:
          descriptor:
            sql.BasicBinder : error
    com.nayasis.simplelauncher : trace
    io.nayasis : trace
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%-5level) %50(\\(%F:%L\\)){blue} : %msg%n"
