spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:file:./db/simplelauncher
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 3
      connection-timeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
  main:
    lazy-initialization: true
